name: CI for fortune-telling-dev branch

on:
  push:
    branches: [fortune-telling-dev]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Super-Linter
    - uses: actions/checkout@v3
      with:
        ref: fortune-telling-dev
        clean: false
    - uses: actions/setup-node@v3
      with:
            node-version: 18

  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@45fc0d88288beee4701c62761281edfee85655d7
    - uses: super-linter/super-linter@v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
