name: CI for fortune-telling-dev branch

on:
  pull_request:

jobs:
  lint:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@45fc0d88288beee4701c62761281edfee85655d7
      uses: super-linter/super-linter@v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
