name: Lint Code Base

on:
  workflow_call:

jobs:
  build:
    name: Build/Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #Adds the test-8ball-PWA branch to the pages
      - uses: actions/checkout@v3
        with:
          ref: test-8ball-PWA
          path: main/test-8ball-PWA
          clean: false
          fetch-depth: 0
      - run: rm -rf main/test-8ball-PWA/.git
      #Adds the fortune-telling-dev branch to the pages
      - uses: actions/checkout@v3
        with:
          ref: fortune-telling-dev
          path: main/fortune-telling-dev
          clean: false
          fetch-depth: 0
      - run: rm -rf main/fortune-telling-dev/.git
      #Adds the documentation branch to the pages
      - uses: actions/checkout@v3
        with:
          ref: documentation
          path: main/documentation
          clean: false
          fetch-depth: 0
      - run: rm -rf main/documentation/.git
      
    #- name: Checkout Code
    #  uses: actions/checkout@v3
    #  with:
    #    fetch-depth: 0
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_HTML: true
        VALIDATE_CSS: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_JSON: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run:
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE