name: Lint Code Base

on:
  workflow_call:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_HTML: true
        VALIDATE_CSS: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_JSON: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}